spring:
#  datasource:
#    url: "jdbc:h2:file:C:/data/demo"
#    password: "password"
#    username: "sa"
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 500
management:
  endpoints:
    jmx:
      exposure:
        include: "health,info"