spring:
  datasource:
    platform: postgres
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: "postgres"
    password: "admin"
  h2:
    console:
      enabled: true
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        lob:
          non_contextual_creation: true
  servlet:
#    configure max allowed file upload size
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


hibernate:
  id:
    new_generator_mappings: true

# configure embedded Tomcat not to cancel the request with large body up to the set size
server:
  tomcat:
    max-swallow-size: 50MB
  servlet:
    context-path: /counselling-app

management:
  endpoints:
    jmx:
      exposure:
        include: "health,info"

# Logging
logging:
  level:
    root: WARN
    org.springframework: INFO
    org.hibernate.*: ERROR
    com.zaxxer.hikari.*: ERROR
    com.vedantu.counselling.data.*: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

# Counselling Data
data:
  maxDistance: 3000

uploadService:
  password: counselling@123
