spring:
  datasource:
    platform: postgres
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: "postgres"
    password: "admin"
  h2:
    console:
      enabled: true
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        lob:
          non_contextual_creation: true

management:
  endpoints:
    jmx:
      exposure:
        include: "health,info"

# Logging
logging:
  level:
    org.springframework: INFO
    org.hibernate.*: ERROR
    com.zaxxer.hikari.*: ERROR
