spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: "postgres"
    password: "admin"
    # url: "jdbc:h2:mem:testdb"
    # driverClassName: org.h2.Driver
    # password: "admin"
    # username: "sa"
  h2:
    console:
      enabled: true
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        lob:
          non_contextual_creation: true

management:
  endpoints:
    jmx:
      exposure:
        include: "health,info"

# Logging
logging:
  level:
    org.springframework: INFO
    org.hibernate.*: ERROR
    com.zaxxer.hikari.*: ERROR
