spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        lob:
          non_contextual_creation: true
  servlet:
#    configure max allowed file upload size
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


hibernate:
  id:
    new_generator_mappings: true

# configure embedded Tomcat not to cancel the request with large body up to the set size
server:
  tomcat:
    max-swallow-size: 50MB
  servlet:
    context-path: /counselling-app

management:
  endpoints:
    jmx:
      exposure:
        include: "health,info"

# Counselling Data
data:
  maxDistance: 3000

uploadService:
  password: counselling@123
