spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: "postgres"
    password: "admin"

logging:
  pattern:
    console: "%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
  level:
    org.springframework: INFO
    org.hibernate.*: ERROR
    com.zaxxer.hikari.*: ERROR
    com.vedantu.counselling.data.*: INFO
    org.hibernate.SQL: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO

cors:
  allowedOrigins: http://localhost:4200