spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://65.1.62.60:5432/counselling-db
    username: postgres
    password: counselling@123

logging:
  file:
    name: logs/counselling-data-service.log
    max-size: 10MB
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
    rolling-file-name: counselling-data-service-%d{yyyy-MM-dd}.%i.log
  level:
    org.springframework: INFO
    org.hibernate.*: ERROR
    com.zaxxer.hikari.*: ERROR
    com.vedantu.counselling.data.*: INFO
    org.hibernate.SQL: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO

cors:
  allowedOrigins: https://vedantu-counselling.herokuapp.com
